name: google_maps_apis
description: Google Maps Web Services [API](https://developers.google.com/maps/web-services)
version: 2.0.0
repository: https://github.com/luis901101/google_maps_apis
issue_tracker: https://github.com/luis901101/google_maps_apis/issues
topics:
  - google-apis
  - google-place
  - google-place-new-api
  - google-directions
  - google-geocoding

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: '>=0.13.0 <2.0.0'
  json_annotation: ^4.9.0
  copy_with_extension: ^6.0.1
  collection: ^1.19.1
  retrofit: ^4.4.2
  dio: ^5.8.0+1
  meta: ^1.16.0
  uuid: ^4.5.1

dev_dependencies:
  test: ^1.25.15
  lints: ^5.1.1
  build_runner: ^2.4.15
  retrofit_generator: ^9.1.9
  json_serializable: ^6.9.4
  copy_with_extension_gen: ^6.0.1
  coverage: ^1.11.1
